### ISSUE TITLE
Getting missing private dependencies issue.

### ISSUE THREAD

**Issue by i-photon** [nasa/PRECiSA#12]
After ghc Setup.hs, I'm getting this:

```
Configuring precisa-4.0.2...
Setup: Encountered missing or private dependencies:
FloatingHex >=0.4,
aeson,
extra,
ieee >=0.7,
optparse-applicative >=0.14,
scientific >=0.3 && <0.4
```

However, I'm not familiar with Haskell, and I'm quite confused by the "fire and forget" tone of the installation instructions.
Nothing was installed after running make. There is no install target for make, which is confusing.

The host is Debian 12.

**Comment by i-photon** [comment]
It looks like I can get away with running "cabal install" from the nested precisa folder. Maybe.

**Comment by lauratitolo** [comment]
You just need to run "make",  not "make install". 
What is it that is confusing for you in the instructions? There is no mention to "make install" there.

**Comment by lauratitolo** [comment]
What version of GHC are you using?

**Comment by i-photon** [comment]
The instructions aren't confusing, its the package manager (cabal) reporting that it installed something, but then it did not. I wasn't sure if I missed something. I used ghc v 9.02 if that helps.
